using System.Windows.Forms.DataVisualization.Charting;

namespace Libreria.UI
{
    partial class FormDashboardVentas
    {
        private System.ComponentModel.IContainer components = null;
        private Label lblRangoSemana;
        private Label lblEstado;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            lblRangoSemana = new Label();
            lblEstado = new Label();
            Label lblTitulo = new Label();
            Panel pnlSemana = new Panel();
            Button btnSemanaAnterior = new Button();
            Button btnSemanaSiguiente = new Button();
            Button btnSemanaActual = new Button();
            GroupBox grpResumen = new GroupBox();
            Label lblTotalTitulo = new Label();
            Label lblTotalValor = new Label();
            Label lblItemsTitulo = new Label();
            Label lblItemsValor = new Label();
            Label lblFacturasTitulo = new Label();
            Label lblFacturasValor = new Label();
            GroupBox grpVentasSemana = new GroupBox();
            GroupBox grpClientes = new GroupBox();
            chartClientes = new Chart();
            Panel pnlGraficoSemana = new Panel();
            GroupBox grpCategorias = new GroupBox();
            Panel pnlCategorias = new Panel();
            Label lblCategorias = new Label();
            Button btnDetalleCategoria = new Button();
            GroupBox grpCategoriasItems = new GroupBox();
            panelCategoriasItems = new Panel();
            GroupBox grpMarcas = new GroupBox();
            lblTituloGraficoMarcas = new Label();
            chartMarcas = new Chart();
            SuspendLayout();
            // lblTitulo
            lblTitulo.AutoSize = true;
            lblTitulo.Font = new Font("Segoe UI", 16F, FontStyle.Bold);
            lblTitulo.Location = new Point(20, 18);
            lblTitulo.Text = "Dashboard de ventas";
            // pnlSemana
            pnlSemana.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            pnlSemana.Location = new Point(20, 61);
            pnlSemana.Size = new Size(1060, 48);
            btnSemanaAnterior.Location = new Point(6, 9);
            btnSemanaAnterior.Size = new Size(32, 30);
            btnSemanaAnterior.Text = "<";
            btnSemanaAnterior.Click += btnSemanaAnterior_Click;
            btnSemanaSiguiente.Location = new Point(48, 9);
            btnSemanaSiguiente.Size = new Size(32, 30);
            btnSemanaSiguiente.Text = ">";
            btnSemanaSiguiente.Click += btnSemanaSiguiente_Click;
            lblRangoSemana.AutoSize = true;
            lblRangoSemana.Font = new Font("Segoe UI", 11F, FontStyle.Bold);
            lblRangoSemana.Location = new Point(98, 14);
            lblRangoSemana.Text = "Semana del 00/00/0000 al 00/00/0000";
            btnSemanaActual.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            btnSemanaActual.Location = new Point(924, 9);
            btnSemanaActual.Size = new Size(130, 30);
            btnSemanaActual.Text = "Semana actual";
            btnSemanaActual.Click += btnSemanaActual_Click;
            pnlSemana.Controls.Add(btnSemanaAnterior);
            pnlSemana.Controls.Add(btnSemanaSiguiente);
            pnlSemana.Controls.Add(lblRangoSemana);
            pnlSemana.Controls.Add(btnSemanaActual);
            // grpResumen
            grpResumen.Anchor = AnchorStyles.Top | AnchorStyles.Left;
            grpResumen.Location = new Point(20, 120);
            grpResumen.Size = new Size(520, 78);
            grpResumen.Text = "Resumen semanal";
            lblTotalTitulo.AutoSize = true;
            lblTotalTitulo.Location = new Point(18, 21);
            lblTotalTitulo.Text = "Total facturado";
            lblTotalValor.AutoSize = true;
            lblTotalValor.Font = new Font("Segoe UI", 14F, FontStyle.Bold);
            lblTotalValor.Location = new Point(18, 39);
            lblTotalValor.Text = ",00";
            lblItemsTitulo.AutoSize = true;
            lblItemsTitulo.Location = new Point(188, 21);
            lblItemsTitulo.Text = "Items vendidos";
            lblItemsValor.AutoSize = true;
            lblItemsValor.Font = new Font("Segoe UI", 14F, FontStyle.Bold);
            lblItemsValor.Location = new Point(188, 39);
            lblItemsValor.Text = "0";
            lblFacturasTitulo.AutoSize = true;
            lblFacturasTitulo.Location = new Point(354, 21);
            lblFacturasTitulo.Text = "Cantidad de facturas";
            lblFacturasValor.AutoSize = true;
            lblFacturasValor.Font = new Font("Segoe UI", 14F, FontStyle.Bold);
            lblFacturasValor.Location = new Point(354, 39);
            lblFacturasValor.Text = "0";
            grpResumen.Controls.Add(lblTotalTitulo);
            grpResumen.Controls.Add(lblTotalValor);
            grpResumen.Controls.Add(lblItemsTitulo);
            grpResumen.Controls.Add(lblItemsValor);
            grpResumen.Controls.Add(lblFacturasTitulo);
            grpResumen.Controls.Add(lblFacturasValor);
            // grpVentasSemana
            grpVentasSemana.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left;
            grpVentasSemana.Location = new Point(20, 214);
            grpVentasSemana.Size = new Size(520, 270);
            grpVentasSemana.Text = "Facturacion por dia de la semana";
            pnlGraficoSemana.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            pnlGraficoSemana.BackColor = SystemColors.Window;
            pnlGraficoSemana.BorderStyle = BorderStyle.FixedSingle;
            pnlGraficoSemana.Location = new Point(18, 28);
            pnlGraficoSemana.Size = new Size(484, 222);
            Panel pnlBarraLun = new Panel();
            Label lblValorLun = new Label();
            Label lblDiaLun = new Label();
            pnlBarraLun.BackColor = Color.SteelBlue;
            pnlBarraLun.Cursor = Cursors.Hand;
            pnlBarraLun.Location = new Point(24, 118);
            pnlBarraLun.Size = new Size(42, 56);
            pnlBarraLun.Tag = 0;
            pnlBarraLun.Click += DiaSemana_Click;
            lblValorLun.Cursor = Cursors.Hand;
            lblValorLun.Location = new Point(5, 95);
            lblValorLun.Size = new Size(78, 20);
            lblValorLun.Tag = 0;
            lblValorLun.Text = "$0";
            lblValorLun.TextAlign = ContentAlignment.MiddleCenter;
            lblValorLun.Click += DiaSemana_Click;
            lblDiaLun.Cursor = Cursors.Hand;
            lblDiaLun.Location = new Point(5, 184);
            lblDiaLun.Size = new Size(78, 24);
            lblDiaLun.Tag = 0;
            lblDiaLun.Text = "Lun";
            lblDiaLun.TextAlign = ContentAlignment.MiddleCenter;
            lblDiaLun.Click += DiaSemana_Click;
            pnlGraficoSemana.Controls.Add(pnlBarraLun);
            pnlGraficoSemana.Controls.Add(lblValorLun);
            pnlGraficoSemana.Controls.Add(lblDiaLun);
            Panel pnlBarraMar = new Panel();
            Label lblValorMar = new Label();
            Label lblDiaMar = new Label();
            pnlBarraMar.BackColor = Color.SteelBlue;
            pnlBarraMar.Cursor = Cursors.Hand;
            pnlBarraMar.Location = new Point(91, 94);
            pnlBarraMar.Size = new Size(42, 80);
            pnlBarraMar.Tag = 1;
            pnlBarraMar.Click += DiaSemana_Click;
            lblValorMar.Cursor = Cursors.Hand;
            lblValorMar.Location = new Point(73, 71);
            lblValorMar.Size = new Size(78, 20);
            lblValorMar.Tag = 1;
            lblValorMar.Text = "$0";
            lblValorMar.TextAlign = ContentAlignment.MiddleCenter;
            lblValorMar.Click += DiaSemana_Click;
            lblDiaMar.Cursor = Cursors.Hand;
            lblDiaMar.Location = new Point(73, 184);
            lblDiaMar.Size = new Size(78, 24);
            lblDiaMar.Tag = 1;
            lblDiaMar.Text = "Mar";
            lblDiaMar.TextAlign = ContentAlignment.MiddleCenter;
            lblDiaMar.Click += DiaSemana_Click;
            pnlGraficoSemana.Controls.Add(pnlBarraMar);
            pnlGraficoSemana.Controls.Add(lblValorMar);
            pnlGraficoSemana.Controls.Add(lblDiaMar);
            Panel pnlBarraMie = new Panel();
            Label lblValorMie = new Label();
            Label lblDiaMie = new Label();
            pnlBarraMie.BackColor = Color.SteelBlue;
            pnlBarraMie.Cursor = Cursors.Hand;
            pnlBarraMie.Location = new Point(159, 70);
            pnlBarraMie.Size = new Size(42, 104);
            pnlBarraMie.Tag = 2;
            pnlBarraMie.Click += DiaSemana_Click;
            lblValorMie.Cursor = Cursors.Hand;
            lblValorMie.Location = new Point(141, 47);
            lblValorMie.Size = new Size(78, 20);
            lblValorMie.Tag = 2;
            lblValorMie.Text = "$0";
            lblValorMie.TextAlign = ContentAlignment.MiddleCenter;
            lblValorMie.Click += DiaSemana_Click;
            lblDiaMie.Cursor = Cursors.Hand;
            lblDiaMie.Location = new Point(141, 184);
            lblDiaMie.Size = new Size(78, 24);
            lblDiaMie.Tag = 2;
            lblDiaMie.Text = "Mie";
            lblDiaMie.TextAlign = ContentAlignment.MiddleCenter;
            lblDiaMie.Click += DiaSemana_Click;
            pnlGraficoSemana.Controls.Add(pnlBarraMie);
            pnlGraficoSemana.Controls.Add(lblValorMie);
            pnlGraficoSemana.Controls.Add(lblDiaMie);
            Panel pnlBarraJue = new Panel();
            Label lblValorJue = new Label();
            Label lblDiaJue = new Label();
            pnlBarraJue.BackColor = Color.SteelBlue;
            pnlBarraJue.Cursor = Cursors.Hand;
            pnlBarraJue.Location = new Point(226, 104);
            pnlBarraJue.Size = new Size(42, 70);
            pnlBarraJue.Tag = 3;
            pnlBarraJue.Click += DiaSemana_Click;
            lblValorJue.Cursor = Cursors.Hand;
            lblValorJue.Location = new Point(208, 81);
            lblValorJue.Size = new Size(78, 20);
            lblValorJue.Tag = 3;
            lblValorJue.Text = "$0";
            lblValorJue.TextAlign = ContentAlignment.MiddleCenter;
            lblValorJue.Click += DiaSemana_Click;
            lblDiaJue.Cursor = Cursors.Hand;
            lblDiaJue.Location = new Point(208, 184);
            lblDiaJue.Size = new Size(78, 24);
            lblDiaJue.Tag = 3;
            lblDiaJue.Text = "Jue";
            lblDiaJue.TextAlign = ContentAlignment.MiddleCenter;
            lblDiaJue.Click += DiaSemana_Click;
            pnlGraficoSemana.Controls.Add(pnlBarraJue);
            pnlGraficoSemana.Controls.Add(lblValorJue);
            pnlGraficoSemana.Controls.Add(lblDiaJue);
            Panel pnlBarraVie = new Panel();
            Label lblValorVie = new Label();
            Label lblDiaVie = new Label();
            pnlBarraVie.BackColor = Color.SteelBlue;
            pnlBarraVie.Cursor = Cursors.Hand;
            pnlBarraVie.Location = new Point(294, 56);
            pnlBarraVie.Size = new Size(42, 118);
            pnlBarraVie.Tag = 4;
            pnlBarraVie.Click += DiaSemana_Click;
            lblValorVie.Cursor = Cursors.Hand;
            lblValorVie.Location = new Point(276, 33);
            lblValorVie.Size = new Size(78, 20);
            lblValorVie.Tag = 4;
            lblValorVie.Text = "$0";
            lblValorVie.TextAlign = ContentAlignment.MiddleCenter;
            lblValorVie.Click += DiaSemana_Click;
            lblDiaVie.Cursor = Cursors.Hand;
            lblDiaVie.Location = new Point(276, 184);
            lblDiaVie.Size = new Size(78, 24);
            lblDiaVie.Tag = 4;
            lblDiaVie.Text = "Vie";
            lblDiaVie.TextAlign = ContentAlignment.MiddleCenter;
            lblDiaVie.Click += DiaSemana_Click;
            pnlGraficoSemana.Controls.Add(pnlBarraVie);
            pnlGraficoSemana.Controls.Add(lblValorVie);
            pnlGraficoSemana.Controls.Add(lblDiaVie);
            Panel pnlBarraSab = new Panel();
            Label lblValorSab = new Label();
            Label lblDiaSab = new Label();
            pnlBarraSab.BackColor = Color.SteelBlue;
            pnlBarraSab.Cursor = Cursors.Hand;
            pnlBarraSab.Location = new Point(361, 134);
            pnlBarraSab.Size = new Size(42, 40);
            pnlBarraSab.Tag = 5;
            pnlBarraSab.Click += DiaSemana_Click;
            lblValorSab.Cursor = Cursors.Hand;
            lblValorSab.Location = new Point(343, 111);
            lblValorSab.Size = new Size(78, 20);
            lblValorSab.Tag = 5;
            lblValorSab.Text = "$0";
            lblValorSab.TextAlign = ContentAlignment.MiddleCenter;
            lblValorSab.Click += DiaSemana_Click;
            lblDiaSab.Cursor = Cursors.Hand;
            lblDiaSab.Location = new Point(343, 184);
            lblDiaSab.Size = new Size(78, 24);
            lblDiaSab.Tag = 5;
            lblDiaSab.Text = "Sab";
            lblDiaSab.TextAlign = ContentAlignment.MiddleCenter;
            lblDiaSab.Click += DiaSemana_Click;
            pnlGraficoSemana.Controls.Add(pnlBarraSab);
            pnlGraficoSemana.Controls.Add(lblValorSab);
            pnlGraficoSemana.Controls.Add(lblDiaSab);
            Panel pnlBarraDom = new Panel();
            Label lblValorDom = new Label();
            Label lblDiaDom = new Label();
            pnlBarraDom.BackColor = Color.SteelBlue;
            pnlBarraDom.Cursor = Cursors.Hand;
            pnlBarraDom.Location = new Point(429, 142);
            pnlBarraDom.Size = new Size(42, 32);
            pnlBarraDom.Tag = 6;
            pnlBarraDom.Click += DiaSemana_Click;
            lblValorDom.Cursor = Cursors.Hand;
            lblValorDom.Location = new Point(411, 119);
            lblValorDom.Size = new Size(78, 20);
            lblValorDom.Tag = 6;
            lblValorDom.Text = "$0";
            lblValorDom.TextAlign = ContentAlignment.MiddleCenter;
            lblValorDom.Click += DiaSemana_Click;
            lblDiaDom.Cursor = Cursors.Hand;
            lblDiaDom.Location = new Point(411, 184);
            lblDiaDom.Size = new Size(78, 24);
            lblDiaDom.Tag = 6;
            lblDiaDom.Text = "Dom";
            lblDiaDom.TextAlign = ContentAlignment.MiddleCenter;
            lblDiaDom.Click += DiaSemana_Click;
            pnlGraficoSemana.Controls.Add(pnlBarraDom);
            pnlGraficoSemana.Controls.Add(lblValorDom);
            pnlGraficoSemana.Controls.Add(lblDiaDom);
            grpVentasSemana.Controls.Add(pnlGraficoSemana);
            // grpClientes
            grpClientes.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left;
            grpClientes.Location = new Point(20, 494);
            grpClientes.Size = new Size(520, 180);
            grpClientes.Text = "Top 5 clientes por ingresos";
            chartClientes.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            chartClientes.Location = new Point(18, 28);
            chartClientes.Size = new Size(484, 134);
            grpClientes.Controls.Add(chartClientes);
            // grpCategorias
            grpCategorias.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            grpCategorias.Location = new Point(560, 120);
            grpCategorias.Size = new Size(250, 210);
            grpCategorias.Text = "Top 5 categorias por ingresos";
            pnlCategorias.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            pnlCategorias.BackColor = SystemColors.Window;
            pnlCategorias.BorderStyle = BorderStyle.FixedSingle;
            pnlCategorias.Location = new Point(18, 28);
            pnlCategorias.Size = new Size(214, 160);
            lblCategorias.ForeColor = SystemColors.GrayText;
            lblCategorias.Location = new Point(18, 61);
            lblCategorias.Size = new Size(176, 34);
            lblCategorias.Text = "Area del grafico de torta por categorias";
            lblCategorias.TextAlign = ContentAlignment.MiddleCenter;
            pnlCategorias.Controls.Add(lblCategorias);
            btnDetalleCategoria.Anchor = AnchorStyles.Bottom | AnchorStyles.Right;
            btnDetalleCategoria.Enabled = false;
            btnDetalleCategoria.Visible = false;
            btnDetalleCategoria.Location = new Point(181, 388);
            btnDetalleCategoria.Size = new Size(157, 28);
            btnDetalleCategoria.Text = "Ver detalle categoria";
            grpCategorias.Controls.Add(pnlCategorias);
            grpCategorias.Controls.Add(btnDetalleCategoria);
            // grpCategoriasItems
            grpCategoriasItems.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            grpCategoriasItems.Location = new Point(830, 120);
            grpCategoriasItems.Size = new Size(250, 210);
            grpCategoriasItems.Text = "Top 5 categorias por items vendidos";
            panelCategoriasItems.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            panelCategoriasItems.BackColor = SystemColors.Window;
            panelCategoriasItems.BorderStyle = BorderStyle.FixedSingle;
            panelCategoriasItems.Location = new Point(18, 28);
            panelCategoriasItems.Size = new Size(214, 160);
            grpCategoriasItems.Controls.Add(panelCategoriasItems);
            // grpMarcas
            grpMarcas.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            grpMarcas.Location = new Point(560, 340);
            grpMarcas.Size = new Size(520, 304);
            grpMarcas.Text = "Marcas de la categoria seleccionada";
            lblTituloGraficoMarcas.AutoEllipsis = true;
            lblTituloGraficoMarcas.Location = new Point(12, 20);
            lblTituloGraficoMarcas.Size = new Size(496, 20);
            lblTituloGraficoMarcas.Text = "Seleccione una categoria";
            chartMarcas.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            chartMarcas.Location = new Point(18, 46);
            chartMarcas.Size = new Size(484, 236);
            grpMarcas.Controls.Add(lblTituloGraficoMarcas);
            grpMarcas.Controls.Add(chartMarcas);
            lblEstado.Anchor = AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            lblEstado.AutoEllipsis = true;
            lblEstado.ForeColor = SystemColors.GrayText;
            lblEstado.Location = new Point(20, 656);
            lblEstado.Size = new Size(1060, 22);
            lblEstado.Text = "";
            lblEstado.Visible = false;
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(1100, 690);
            Controls.Add(lblEstado);
            Controls.Add(grpMarcas);
            Controls.Add(grpCategoriasItems);
            Controls.Add(grpCategorias);
            Controls.Add(grpClientes);
            Controls.Add(grpVentasSemana);
            Controls.Add(grpResumen);
            Controls.Add(pnlSemana);
            Controls.Add(lblTitulo);
            MinimumSize = new Size(1000, 650);
            Name = "FormDashboardVentas";
            StartPosition = FormStartPosition.CenterScreen;
            Text = "Dashboard de ventas";
            ResumeLayout(false);
            PerformLayout();
        }
    }
}












