namespace Libreria.UI
{
    partial class FormDashboardVentasDiarias
    {
        private System.ComponentModel.IContainer components = null;
        private Label lblDia;
        private Label lblRangoHorario;
        private Label lblEstado;
        private Button btnBloqueAnterior;
        private Button btnBloqueSiguiente;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            lblDia = new Label();
            lblRangoHorario = new Label();
            lblEstado = new Label();
            btnBloqueAnterior = new Button();
            btnBloqueSiguiente = new Button();
            Label lblTitulo = new Label();
            Panel pnlHorario = new Panel();
            Button btnPrimerBloque = new Button();
            GroupBox grpResumen = new GroupBox();
            Label lblTotalTitulo = new Label();
            Label lblTotalValor = new Label();
            Label lblFacturasTitulo = new Label();
            Label lblFacturasValor = new Label();
            GroupBox grpHoras = new GroupBox();
            Panel pnlGraficoHoras = new Panel();
            GroupBox grpCategorias = new GroupBox();
            Panel pnlCategorias = new Panel();
            Label lblCategorias = new Label();
            SuspendLayout();
            lblTitulo.AutoSize = true;
            lblTitulo.Font = new Font("Segoe UI", 16F, FontStyle.Bold);
            lblTitulo.Location = new Point(20, 18);
            lblTitulo.Text = "Dashboard de ventas diarias";
            lblDia.AutoSize = true;
            lblDia.Font = new Font("Segoe UI", 11F, FontStyle.Bold);
            lblDia.Location = new Point(20, 62);
            lblDia.Text = "Ventas del dia 00/00/0000";
            pnlHorario.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            pnlHorario.Location = new Point(20, 94);
            pnlHorario.Size = new Size(960, 48);
            btnBloqueAnterior.Location = new Point(6, 9);
            btnBloqueAnterior.Size = new Size(32, 30);
            btnBloqueAnterior.Text = "<";
            btnBloqueAnterior.Click += btnBloqueAnterior_Click;
            btnBloqueSiguiente.Location = new Point(48, 9);
            btnBloqueSiguiente.Size = new Size(32, 30);
            btnBloqueSiguiente.Text = ">";
            btnBloqueSiguiente.Click += btnBloqueSiguiente_Click;
            lblRangoHorario.AutoSize = true;
            lblRangoHorario.Font = new Font("Segoe UI", 11F, FontStyle.Bold);
            lblRangoHorario.Location = new Point(98, 14);
            lblRangoHorario.Text = "Horas 00:00 a 05:59";
            btnPrimerBloque.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            btnPrimerBloque.Location = new Point(820, 9);
            btnPrimerBloque.Size = new Size(134, 30);
            btnPrimerBloque.Text = "Ir a 00-05";
            btnPrimerBloque.Click += btnPrimerBloque_Click;
            pnlHorario.Controls.Add(btnBloqueAnterior);
            pnlHorario.Controls.Add(btnBloqueSiguiente);
            pnlHorario.Controls.Add(lblRangoHorario);
            pnlHorario.Controls.Add(btnPrimerBloque);
            grpResumen.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            grpResumen.Location = new Point(20, 153);
            grpResumen.Size = new Size(960, 78);
            grpResumen.Text = "Resumen del dia";
            lblTotalTitulo.AutoSize = true;
            lblTotalTitulo.Location = new Point(18, 21);
            lblTotalTitulo.Text = "Total facturado";
            lblTotalValor.AutoSize = true;
            lblTotalValor.Font = new Font("Segoe UI", 14F, FontStyle.Bold);
            lblTotalValor.Location = new Point(18, 39);
            lblTotalValor.Text = ",00";
            lblFacturasTitulo.AutoSize = true;
            lblFacturasTitulo.Location = new Point(352, 21);
            lblFacturasTitulo.Text = "Cantidad de facturas";
            lblFacturasValor.AutoSize = true;
            lblFacturasValor.Font = new Font("Segoe UI", 14F, FontStyle.Bold);
            lblFacturasValor.Location = new Point(352, 39);
            lblFacturasValor.Text = "0";
            grpResumen.Controls.Add(lblTotalTitulo);
            grpResumen.Controls.Add(lblTotalValor);
            grpResumen.Controls.Add(lblFacturasTitulo);
            grpResumen.Controls.Add(lblFacturasValor);
            grpHoras.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left;
            grpHoras.Location = new Point(20, 247);
            grpHoras.Size = new Size(610, 330);
            grpHoras.Text = "Facturacion por hora";
            pnlGraficoHoras.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            pnlGraficoHoras.BackColor = SystemColors.Window;
            pnlGraficoHoras.BorderStyle = BorderStyle.FixedSingle;
            pnlGraficoHoras.Location = new Point(18, 28);
            pnlGraficoHoras.Size = new Size(574, 282);
            Panel pnlBarraH00 = new Panel();
            Label lblValorH00 = new Label();
            Label lblHoraH00 = new Label();
            pnlBarraH00.BackColor = Color.SeaGreen;
            pnlBarraH00.Location = new Point(38, 174);
            pnlBarraH00.Size = new Size(42, 64);
            lblValorH00.Location = new Point(20, 151);
            lblValorH00.Size = new Size(78, 20);
            lblValorH00.Text = "$0";
            lblValorH00.TextAlign = ContentAlignment.MiddleCenter;
            lblHoraH00.Location = new Point(20, 245);
            lblHoraH00.Size = new Size(78, 24);
            lblHoraH00.Text = "00";
            lblHoraH00.TextAlign = ContentAlignment.MiddleCenter;
            pnlGraficoHoras.Controls.Add(pnlBarraH00);
            pnlGraficoHoras.Controls.Add(lblValorH00);
            pnlGraficoHoras.Controls.Add(lblHoraH00);
            Panel pnlBarraH01 = new Panel();
            Label lblValorH01 = new Label();
            Label lblHoraH01 = new Label();
            pnlBarraH01.BackColor = Color.SeaGreen;
            pnlBarraH01.Location = new Point(132, 146);
            pnlBarraH01.Size = new Size(42, 92);
            lblValorH01.Location = new Point(114, 123);
            lblValorH01.Size = new Size(78, 20);
            lblValorH01.Text = "$0";
            lblValorH01.TextAlign = ContentAlignment.MiddleCenter;
            lblHoraH01.Location = new Point(114, 245);
            lblHoraH01.Size = new Size(78, 24);
            lblHoraH01.Text = "01";
            lblHoraH01.TextAlign = ContentAlignment.MiddleCenter;
            pnlGraficoHoras.Controls.Add(pnlBarraH01);
            pnlGraficoHoras.Controls.Add(lblValorH01);
            pnlGraficoHoras.Controls.Add(lblHoraH01);
            Panel pnlBarraH02 = new Panel();
            Label lblValorH02 = new Label();
            Label lblHoraH02 = new Label();
            pnlBarraH02.BackColor = Color.SeaGreen;
            pnlBarraH02.Location = new Point(226, 200);
            pnlBarraH02.Size = new Size(42, 38);
            lblValorH02.Location = new Point(208, 177);
            lblValorH02.Size = new Size(78, 20);
            lblValorH02.Text = "$0";
            lblValorH02.TextAlign = ContentAlignment.MiddleCenter;
            lblHoraH02.Location = new Point(208, 245);
            lblHoraH02.Size = new Size(78, 24);
            lblHoraH02.Text = "02";
            lblHoraH02.TextAlign = ContentAlignment.MiddleCenter;
            pnlGraficoHoras.Controls.Add(pnlBarraH02);
            pnlGraficoHoras.Controls.Add(lblValorH02);
            pnlGraficoHoras.Controls.Add(lblHoraH02);
            Panel pnlBarraH03 = new Panel();
            Label lblValorH03 = new Label();
            Label lblHoraH03 = new Label();
            pnlBarraH03.BackColor = Color.SeaGreen;
            pnlBarraH03.Location = new Point(320, 112);
            pnlBarraH03.Size = new Size(42, 126);
            lblValorH03.Location = new Point(302, 89);
            lblValorH03.Size = new Size(78, 20);
            lblValorH03.Text = "$0";
            lblValorH03.TextAlign = ContentAlignment.MiddleCenter;
            lblHoraH03.Location = new Point(302, 245);
            lblHoraH03.Size = new Size(78, 24);
            lblHoraH03.Text = "03";
            lblHoraH03.TextAlign = ContentAlignment.MiddleCenter;
            pnlGraficoHoras.Controls.Add(pnlBarraH03);
            pnlGraficoHoras.Controls.Add(lblValorH03);
            pnlGraficoHoras.Controls.Add(lblHoraH03);
            Panel pnlBarraH04 = new Panel();
            Label lblValorH04 = new Label();
            Label lblHoraH04 = new Label();
            pnlBarraH04.BackColor = Color.SeaGreen;
            pnlBarraH04.Location = new Point(414, 160);
            pnlBarraH04.Size = new Size(42, 78);
            lblValorH04.Location = new Point(396, 137);
            lblValorH04.Size = new Size(78, 20);
            lblValorH04.Text = "$0";
            lblValorH04.TextAlign = ContentAlignment.MiddleCenter;
            lblHoraH04.Location = new Point(396, 245);
            lblHoraH04.Size = new Size(78, 24);
            lblHoraH04.Text = "04";
            lblHoraH04.TextAlign = ContentAlignment.MiddleCenter;
            pnlGraficoHoras.Controls.Add(pnlBarraH04);
            pnlGraficoHoras.Controls.Add(lblValorH04);
            pnlGraficoHoras.Controls.Add(lblHoraH04);
            Panel pnlBarraH05 = new Panel();
            Label lblValorH05 = new Label();
            Label lblHoraH05 = new Label();
            pnlBarraH05.BackColor = Color.SeaGreen;
            pnlBarraH05.Location = new Point(508, 88);
            pnlBarraH05.Size = new Size(42, 150);
            lblValorH05.Location = new Point(490, 65);
            lblValorH05.Size = new Size(78, 20);
            lblValorH05.Text = "$0";
            lblValorH05.TextAlign = ContentAlignment.MiddleCenter;
            lblHoraH05.Location = new Point(490, 245);
            lblHoraH05.Size = new Size(78, 24);
            lblHoraH05.Text = "05";
            lblHoraH05.TextAlign = ContentAlignment.MiddleCenter;
            pnlGraficoHoras.Controls.Add(pnlBarraH05);
            pnlGraficoHoras.Controls.Add(lblValorH05);
            pnlGraficoHoras.Controls.Add(lblHoraH05);
            grpHoras.Controls.Add(pnlGraficoHoras);
            grpCategorias.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            grpCategorias.Location = new Point(648, 247);
            grpCategorias.Size = new Size(332, 330);
            grpCategorias.Text = "Top 5 categorias mas vendidas";
            pnlCategorias.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            pnlCategorias.BackColor = SystemColors.Window;
            pnlCategorias.BorderStyle = BorderStyle.FixedSingle;
            pnlCategorias.Location = new Point(18, 28);
            pnlCategorias.Size = new Size(296, 282);
            lblCategorias.ForeColor = SystemColors.GrayText;
            lblCategorias.Location = new Point(38, 123);
            lblCategorias.Size = new Size(220, 34);
            lblCategorias.Text = "Area del grafico de categorias del dia";
            lblCategorias.TextAlign = ContentAlignment.MiddleCenter;
            pnlCategorias.Controls.Add(lblCategorias);
            grpCategorias.Controls.Add(pnlCategorias);
            lblEstado.Anchor = AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            lblEstado.AutoEllipsis = true;
            lblEstado.ForeColor = SystemColors.GrayText;
            lblEstado.Location = new Point(20, 596);
            lblEstado.Size = new Size(960, 22);
            lblEstado.Text = "Vista diaria preparada. Falta conectar los datos de ventas.";
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(1000, 630);
            Controls.Add(lblEstado);
            Controls.Add(grpCategorias);
            Controls.Add(grpHoras);
            Controls.Add(grpResumen);
            Controls.Add(pnlHorario);
            Controls.Add(lblDia);
            Controls.Add(lblTitulo);
            MinimumSize = new Size(900, 580);
            Name = "FormDashboardVentasDiarias";
            StartPosition = FormStartPosition.CenterScreen;
            Text = "Dashboard de ventas diarias";
            ResumeLayout(false);
            PerformLayout();
        }
    }
}
